export interface SpeechTexts {
  ru: string;
  en: string;
}

export const Speech: { [key: number]: SpeechTexts } = {
  0: {
    ru: `💫 Оформить подписку - НАПИСАТЬ СЮДА ТЕКСТ ДЛЯ ПЕРВОГО КВЕСТА`,
    en: `💫 Subscribe - WRITE TEXT FOR THE FIRST QUEST`,
  },
  1: {
    ru: `Нейрокоманда: Цифровое тело аватара. Создайте визуальный облик аватара для изображений и видео, отражая вашу индивидуальность. Используйте технологию Флакс для персонализации с помощью ваших фотографий. Выберите количество шагов обучения от одной тысячи до шести тысяч для детализации. Подготовьте минимум десять фотографий с разнообразием ракурсов, выражений, освещения и стилей одежды. После загрузки бот обучается от одного до трех часов. Затем используйте модель для создания уникальных изображений и видео с командой "Нейрофото". Чтобы воспользоваться командой, пригласите друга и создавайте уникальный аватар вместе.`,
    en: `Neurocommand: Digital Avatar Body. Create an avatar's visual identity for images and videos that reflects your personality. Use Flux technology to personalize with your photos. Choose the number of training steps from one thousand to six thousand for detail. Prepare at least ten photos with a variety of angles, expressions, lighting, and clothing styles. Once uploaded, the bot will train for one to three hours. Then use the model to create unique images and videos with the NeuroPhoto command. To use the command, invite a friend and create a unique avatar together`,
  },
  2: {
    ru: `Нейрокоманда: Нейрофото. После создания цифрового тела аватара используйте его для создания нейрофото — изображений, преобразующих текстовые описания в уникальные визуальные образы с вашим лицом. Это инновационный способ визуализировать идеи. Начните с выбора команды "Нейрофото" в меню бота. Создайте детализированное текстовое описание, которое станет основой для изображения. Отправьте описание боту, и он начнет генерацию, что займет несколько секунд. После завершения вы получите нейрофото, которое можно использовать для личных или профессиональных целей. Чтобы воспользоваться командой, пригласите друга и создавайте уникальный аватар вместе.`,
    en: `Neurocommand: Neurophoto. After creating the avatar's digital body, use it to create neurophotos — images that transform text descriptions into unique visual forms with your face. This is an innovative way to visualize ideas. Start by selecting the "Neurophoto" command in the bot menu. Create a detailed text description that will serve as the basis for the image. Send the description to the bot, and it will begin generation, which will take a few seconds. After completion, you will receive a neurophoto that you can use for personal or professional purposes. To use the command, invite a friend and create an avatar together.`,
  },
  3: {
    ru: `Нейрокоманда: ПРОМПТ ИЗ ФОТО. Эта функция позволяет преобразовать визуальные данные в текст, создавая промпт для нейрофото. Это полезно для создания описаний изображений, анализа контента или развлечения. Детализированный промпт улучшает качество нейрофото, повышая точность и выразительность изображений. Процесс использования: выберите четкое и качественное изображение, например, супермена или русалки. Отправьте его боту для анализа. После анализа вы получите текстовое описание, отражающее содержимое изображения, включая цвета, формы и объекты. Чтобы воспользоваться командой, пригласите друга и создавайте уникальный аватар вместе.`,
    en: `Neurocommand: PHOTO PROMPT. This feature allows you to convert visual data into text, creating a prompt for a neurophoto. It is useful for creating image descriptions, content analysis or entertainment. A detailed prompt improves the quality of neurophotos, increasing the accuracy and expressiveness of images. How to use: Choose a clear and high-quality image, such as Superman or a mermaid. Send it to the bot for analysis. The bot uses algorithms and neural networks to recognize objects and scenes, which may take time. After analysis, you will receive a text description reflecting the content of the image, including colors, shapes and objects. To use the command, invite a friend and create an avatar together.`,
  },
  4: {
    ru: `Нейрокоманда: Мозг аватара. Создайте интеллектуальное ядро аватара, указав название компании, вашу должность и навыки. Это позволит аватару адаптироваться к вам и учитывать ваши профессиональные способности. Бот создаст ядро, превращая аватара в цифрового помощника, который будет поддерживать вас в различных ситуациях, от профессиональных встреч до личных проектов. Преимущества включают персонализацию, эффективность и внедрение инноваций в вашу работу. Чтобы воспользоваться командой, пригласите друга и создавайте уникальный аватар вместе.`,
    en: `Neurocommand: Avatar Brain. Create an avatar’s intelligent core by entering your company name, job title, and skills. This will allow the avatar to adapt to you and take into account your professional abilities. The bot will create the core, turning the avatar into a digital assistant that will support you in various situations, from professional meetings to personal projects. Benefits include personalization, efficiency, and innovation in your work. To use the team, invite a friend and create a unique avatar together.`,
  },
  5: {
    ru: `Нейрокоманда: ЧАТ С АВАТАРОМ. Начните общение с аватаром, открывая новые горизонты. Пишите в чат, и аватар ответит, используя ИИ, делая беседу естественной. Задавайте вопросы, делитесь мыслями. Аватар может быть формальным или неформальным, создавая уникальный опыт. Полезно для обучения и терапии. Используйте для советов или расслабления. Чтобы воспользоваться командой, пригласите друга и создавайте уникальный аватар вместе.`,
    en: `Neurocommand: CHAT WITH AVATAR. Start a conversation with your avatar, opening new horizons. Write in the chat, and the avatar will respond using AI, making the conversation natural. Ask questions, share thoughts. The avatar can be formal or informal, creating a unique experience. Useful for training and therapy. Use for advice or relaxation. To use the team, invite a friend and start creating a unique avatar together.`,
  },
  6: {
    ru: `Нейрокоманда: ВЫБОР МОДЕЛИ ИИ. Выберите подходящую модель для ваших задач, улучшая качество и точность результатов. Вызовите команду в интерфейсе бота, чтобы увидеть список моделей с уникальными характеристиками. Например, одна модель подходит для креативного текста, другая — для аналитики. Выберите модель, соответствующую вашим потребностям. После выбора используйте её для генерации текста. Преимущества: персонализация и оптимизация задач. Команда "Выбор модели ИИ" позволяет гибко использовать бота. Чтобы воспользоваться командой, пригласите друга и создавайте уникальный аватар вместе.`,
    en: `Neurocommand: SELECT AI MODEL. Choose the right model for your tasks, improving the quality and accuracy of results. Call the command in the bot interface to see a list of models with unique characteristics. For example, one model is suitable for creative text, another for analytics. Choose the model that suits your needs. Once selected, use it to generate text. Benefits: personalization and optimization of tasks. The "Select AI model" command allows you to use the bot flexibly. To use the command, invite a friend and create a unique avatar together`,
  },
  7: {
    ru: `Нейрокоманда: ГОЛОС ДЛЯ АВАТАРА. Делает аватар живым и выразительным, полезным в презентациях и видео. Как начать: Запишите голосовое сообщение. Используйте хороший микрофон, записывайте в тихом месте, говорите четко и с эмоциями. Длительность записи — сорок-шестьдесят секунд. Отправьте запись боту для создания голосового аватара. После завершения получите готовый аватар для использования. Преимущества: уникальность контента и экономия времени на озвучивание. Функция персонализирует ваш цифровой образ. Чтобы воспользоваться командой, пригласите друга и создавайте уникальный аватар вместе.`,
    en: `Neurocommand: VOICE FOR AVATAR. Makes your avatar lively and expressive, useful in presentations and videos. How to start: Record a voice message. Use a good microphone, record in a quiet place, speak clearly and with emotion. Recording duration is forty to sixty seconds. Send the recording to the bot to create a voice avatar. Once completed, receive a ready-made avatar for use. Benefits: content uniqueness and time-saving on voice-over. The function personalizes your digital image.`,
  },
  8: {
    ru: `Нейрокоманда: ТЕКСТ В ГОЛОС. Используйте для озвучивания текстов, создавая аудиоконтент для презентаций и видео. В меню бота выберите "Текст в голос", напишите и отправьте четкий текст. Бот преобразует его в голос с вашим голосовым аватаром, и вы получите аудиофайл. Преимущества: персонализация добавляет уникальность контенту, а эффективность обеспечивает быстрое преобразование текста в голос. Функция делает контент более живым. Чтобы воспользоваться командой, пригласите друга и создавайте уникальный аватар вместе.`,
    en: `Neurocommand: TEXT TO VOICE. Use it to voice texts, creating audio content for presentations and videos. Select "Text to voice" in the bot menu, write and send a clear text. The bot converts it to voice using your voice avatar, and you get an audio file. Benefits: personalization adds uniqueness to content, and efficiency ensures quick text-to-voice conversion. The function makes content more lively. To use the command, invite a friend and create an avatar together.`,
  },
  9: {
    ru: `Нейрокоманда: ФОТО В ВИДЕО. Оживите статические изображения с вашим аватаром, добавляя движение и динамику. Это открывает новые горизонты для творчества, превращая идеи в видеоролики. Процесс использования: выберите модель генерации видео, загрузите качественное изображение, опишите желаемое движение, и бот создаст уникальное видео. Функция добавляет глубину и выразительность проектам. Чтобы воспользоваться командой, пригласите друга и создавайте уникальный аватар вместе.`,
    en: `Neurocommand: PHOTO IN VIDEO. Bring static images to life with your avatar, adding movement and dynamics. This opens new horizons for creativity, turning ideas into videos. Usage process: select a video generation model, upload a quality image, describe the desired movement, and the bot will create a unique video. The function adds depth and expressiveness to projects. To use the command, invite a friend and create an avatar together.`,
  },
  10: {
    ru: `Нейрокоманда: ВИДЕО ИЗ ТЕКСТА. Превратите идеи в видеоролики с помощью текстового описания. Начните с выбора модели генерации видео, соответствующей вашим потребностям. Создайте детализированное текстовое описание для генерации видео. Отправьте промпт боту, и он начнет генерацию. После завершения получите видео для личных или профессиональных целей. Экспериментируйте с моделями, чтобы найти подходящую для вашего проекта. Чтобы воспользоваться командой, пригласите друга и создавайте уникальный аватар вместе.`,
    en: `Neurocommand: VIDEO FROM TEXT. Turn ideas into videos using text descriptions. Start by choosing a video generation model that suits your needs. Create a detailed text description for video generation. Send the prompt to the bot, and it will start generating. Once completed, get a video for personal or professional purposes. Experiment with models to find the right one for your project. To use the command, invite a friend and create an avatar together.`,
  },
  11: {
    ru: `Нейрокоманда: Текст в фото. Превратите идеи в визуальную форму с помощью текстового описания. Выберите одну из нескольких моделей генерации изображений, каждая с уникальными характеристиками. Это позволяет адаптировать процесс под ваши нужды. Экспериментируйте с моделями, чтобы найти подходящую для вашего проекта. Это позволит создавать уникальные визуальные образы, точно отражающие ваши идеи. Например, введите 'закат над океаном', и бот создаст изображение с яркими оттенками неба. Чтобы воспользоваться командой, пригласите друга и создавайте уникальный аватар вместе.`,
    en: `Neurocommand: Text to Photo. Turn your ideas into visual form using text descriptions. Choose from several image generation models, each with unique characteristics. This allows you to tailor the process to your needs. Experiment with models to find the right one for your project. This will allow you to create unique visual images that accurately reflect your ideas. For example, type 'sunset over the ocean' and the bot will create an image with bright sky hues. To use the command, invite a friend and create an avatar together.`,
  },
};
